In [1]:
from pathlib import Path
from zipfile import ZipFile
from tqdm import tqdm
import pandas as pd

In [ ]:
# Extraction des datasets
data_dir = Path("data/prod/zip/regional")
out_dir = Path("data/prod/unzipped/regional")
out_dir.mkdir(parents=True, exist_ok=True)

# Liste de toutes les archives zip
zip_files = sorted(data_dir.glob("*.zip"))

# Barre de progression
for z in tqdm(zip_files, desc="Extraction des fichiers", unit="archive"):
    with ZipFile(z) as zf:
        zf.extractall(out_dir)

Extraction des fichiers: 100%|██████████| 11/11 [00:00<00:00, 103.55archive/s]

In [ ]:
data_dir = Path("data/prod/unzipped/regional")

# Liste de tous les fichiers .xlsx
xlsx_files = sorted(data_dir.glob("*.xlsx"))

# Chargement et concaténation
dfs = []
for file in xlsx_files:
    df = pd.read_excel(file)
    #df["source_file"] = file.stem
    dfs.append(df)

# Concaténation de tous les DataFrames
df_all = pd.concat(dfs, ignore_index=True)

print(f"{len(dfs)} fichiers chargés")
print(df_all.shape)
df_all.head()

3 fichiers chargés
(105123, 67)

,Périmètre,Nature,Date,Heures,Consommation,Thermique,Nucléaire,Eolien,Solaire,Hydraulique,...,TCO Nucléaire (%),TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%)
0,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,00:00:00,8586.0,156.0,10710.0,66.0,0.0,3096.0,...,124.74,78.92,0.77,11.81,0.0,0.0,36.06,26.25,1.55,71.12
1,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,00:15:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,00:30:00,8373.0,179.0,10622.0,64.0,0.0,2977.0,...,126.86,78.28,0.76,11.45,0.0,0.0,35.55,25.24,1.45,64.71
3,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,00:45:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,01:00:00,8134.0,181.0,10652.0,58.0,0.0,2667.0,...,130.96,78.50,0.71,10.38,0.0,0.0,32.79,22.61,1.49,64.71

In [3]:
df_all = df_all[~df_all["Heures"].astype(str).str.endswith(("15:00", "45:00"))]

In [4]:
df_all.to_csv("data/eCO2mix_RTE_Auvergne-Rhone-Alpes_extract.csv", index=False)

In [5]:
df_all.shape

(52563, 67)

In [6]:
df_all.head()

,Périmètre,Nature,Date,Heures,Consommation,Thermique,Nucléaire,Eolien,Solaire,Hydraulique,...,TCO Nucléaire (%),TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%)
0,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,00:00:00,8586.0,156.0,10710.0,66.0,0.0,3096.0,...,124.74,78.92,0.77,11.81,0.0,0.0,36.06,26.25,1.55,71.12
2,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,00:30:00,8373.0,179.0,10622.0,64.0,0.0,2977.0,...,126.86,78.28,0.76,11.45,0.0,0.0,35.55,25.24,1.45,64.71
4,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,01:00:00,8134.0,181.0,10652.0,58.0,0.0,2667.0,...,130.96,78.50,0.71,10.38,0.0,0.0,32.79,22.61,1.49,64.71
6,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,01:30:00,8130.0,179.0,10662.0,54.0,0.0,2592.0,...,131.14,78.57,0.66,9.66,0.0,0.0,31.88,21.98,1.50,65.24
8,Auvergne-Rhône-Alpes,Données définitives,2021-01-01,02:00:00,8102.0,181.0,10600.0,42.0,0.0,2827.0,...,130.83,78.11,0.52,7.51,0.0,0.0,34.89,23.97,1.48,64.17