In [1]:
from pathlib import Path
from zipfile import ZipFile
from tqdm import tqdm
import pandas as pd

In [ ]:
# Extraction des datasets
data_dir = Path("../../data/prod/zip/national")
out_dir = Path("../../data/prod/unzipped/national")
out_dir.mkdir(parents=True, exist_ok=True)

# Liste de toutes les archives zip
zip_files = sorted(data_dir.glob("*.zip"))

# Barre de progression
for z in tqdm(zip_files, desc="Extraction des fichiers", unit="archive"):
    with ZipFile(z) as zf:
        zf.extractall(out_dir)

Extraction des fichiers: 100%|██████████| 12/12 [00:00<00:00, 56.55archive/s]

In [2]:
data_dir = Path("../../data/prod/unzipped/national")

# Liste de tous les fichiers .xlsx
xlsx_files = sorted(data_dir.glob("*.xlsx"))

# Chargement et concaténation
dfs = []
for file in xlsx_files:
    df = pd.read_excel(file)
    #df["source_file"] = file.stem
    dfs.append(df)

# Concaténation de tous les DataFrames
df_all = pd.concat(dfs, ignore_index=True)

print(f"{len(dfs)} fichiers chargés")
print(df_all.shape)
df_all.head()

13 fichiers chargés
(455917, 40)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2012-01-01,00:00:00,58315.0,58200.0,58200.0,492.0,25.0,3816.0,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
1,France,Données définitives,2012-01-01,00:15:00,NaN,57700.0,57550.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2012-01-01,00:30:00,58315.0,57200.0,56900.0,492.0,25.0,3816.0,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
3,France,Données définitives,2012-01-01,00:45:00,NaN,56200.0,56000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2012-01-01,01:00:00,56231.0,55200.0,55100.0,492.0,25.0,3834.0,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN

In [3]:
df_all = df_all[~df_all["Heures"].astype(str).str.endswith(("15:00", "45:00"))]

In [4]:
df_all.to_csv("../../data/prod/eCO2mix_RTE_Annuel-Definitif.csv", index=False)

In [5]:
df_all.shape

(227965, 40)

In [6]:
df.head()

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données consolidées,2024-01-01,00:00:00,55239.0,55000.0,54200.0,96.0,18.0,1975.0,...,5001.0,1553.0,117.0,510.0,354.0,347.0,0.0,0.0,14976.0,581.0
1,France,Données consolidées,2024-01-01,00:15:00,NaN,54300.0,53400.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données consolidées,2024-01-01,00:30:00,54560.0,53600.0,52600.0,96.0,17.0,1919.0,...,4937.0,1569.0,6.0,510.0,355.0,347.0,0.0,0.0,14880.0,579.0
3,France,Données consolidées,2024-01-01,00:45:00,NaN,53200.0,51950.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données consolidées,2024-01-01,01:00:00,52689.0,52800.0,51300.0,95.0,17.0,2000.0,...,4910.0,1179.0,6.0,513.0,359.0,344.0,0.0,0.0,14773.0,582.0