In [19]:
from pathlib import Path
from zipfile import ZipFile
from tqdm import tqdm
import pandas as pd

In [ ]:
# Extraction des datasets
data_dir = Path("data/prod/zip/national")
out_dir = Path("data/prod/unzipped/national")
out_dir.mkdir(parents=True, exist_ok=True)

# Liste de toutes les archives zip
zip_files = sorted(data_dir.glob("*.zip"))

# Barre de progression
for z in tqdm(zip_files, desc="Extraction des fichiers", unit="archive"):
    with ZipFile(z) as zf:
        zf.extractall(out_dir)

Extraction des fichiers: 100%|██████████| 12/12 [00:00<00:00, 56.55archive/s]

In [ ]:
data_dir = Path("data/prod/unzipped/national")

# Liste de tous les fichiers .xlsx
xlsx_files = sorted(data_dir.glob("*.xlsx"))

# Chargement et concaténation
dfs = []
for file in xlsx_files:
    df = pd.read_excel(file)
    #df["source_file"] = file.stem
    dfs.append(df)

# Concaténation de tous les DataFrames
df_all = pd.concat(dfs, ignore_index=True)

print(f"{len(dfs)} fichiers chargés")
print(df_all.shape)
df_all.head()

12 fichiers chargés
(420780, 40)

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2012-01-01,00:00:00,58315.0,58200.0,58200.0,492.0,25.0,3816.0,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
1,France,Données définitives,2012-01-01,00:15:00,NaN,57700.0,57550.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2012-01-01,00:30:00,58315.0,57200.0,56900.0,492.0,25.0,3816.0,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
3,France,Données définitives,2012-01-01,00:45:00,NaN,56200.0,56000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2012-01-01,01:00:00,56231.0,55200.0,55100.0,492.0,25.0,3834.0,...,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN

In [22]:
df_all = df_all[~df_all["Heures"].astype(str).str.endswith(("15:00", "45:00"))]

In [23]:
df_all.to_csv("data/eCO2mix_RTE_Annuel-Definitif.csv", index=False)

In [24]:
df_all.shape

(210396, 40)

In [25]:
df.head()

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,...,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz,Stockage batterie,Déstockage batterie,Eolien terrestre,Eolien offshore
0,France,Données définitives,2023-01-01,00:00:00,47571.0,46600.0,48000.0,81.0,24.0,2418.0,...,4987.0,1224.0,743.0,534.0,431.0,333.0,0.0,0.0,14967.0,405.0
1,France,Données définitives,2023-01-01,00:15:00,NaN,46050.0,47500.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,France,Données définitives,2023-01-01,00:30:00,46342.0,45500.0,47000.0,68.0,24.0,2423.0,...,4792.0,1048.0,842.0,537.0,426.0,337.0,0.0,0.0,13847.0,404.0
3,France,Données définitives,2023-01-01,00:45:00,NaN,44650.0,46350.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,Données définitives,2023-01-01,01:00:00,44790.0,43800.0,45700.0,67.0,25.0,2445.0,...,4781.0,1195.0,891.0,537.0,426.0,338.0,0.0,0.0,11471.0,404.0